name: automated test

# Trigger whenever PR activity happens on review branch
on:
  pull_request:
    branches:
      - review
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
      env:
        CI: true
    - name: build
      run: npm run build
      env:
        CI: true
    - name: test
      run: npm run test-ci
      env:
        CI: true